//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CfcaApiTestClient {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class CFCAAPI : global::System.Configuration.ApplicationSettingsBase {
        
        private static CFCAAPI defaultInstance = ((CFCAAPI)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CFCAAPI())));
        
        public static CFCAAPI Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9ByjWGN0dVK3qsxY")]
        public string PrivateAESKey {
            get {
                return ((string)(this["PrivateAESKey"]));
            }
            set {
                this["PrivateAESKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20171024094122")]
        public string PrivateAESKeyTime {
            get {
                return ((string)(this["PrivateAESKeyTime"]));
            }
            set {
                this["PrivateAESKeyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SDGr4234gG465356")]
        public string FixedAESKey {
            get {
                return ((string)(this["FixedAESKey"]));
            }
            set {
                this["FixedAESKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xadiapdfaxi0s91D")]
        public string FixedAESIV {
            get {
                return ((string)(this["FixedAESIV"]));
            }
            set {
                this["FixedAESIV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BB170802CS")]
        public string UserAccount {
            get {
                return ((string)(this["UserAccount"]));
            }
            set {
                this["UserAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://210.74.42.39/dataservice/")]
        public string APIUrl {
            get {
                return ((string)(this["APIUrl"]));
            }
            set {
                this["APIUrl"] = value;
            }
        }
    }
}
